services:
  - type: web
    name: where-is-my-order
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
